spring:
  application:
    name: football-obs-backend

api:
  cdn-url: ${CDN_URL}
  media-cdn-url: ${MEDIA_CDN_URL}

# TODO: Render 배포 시 CORS_ALLOWED_ORIGINS 환경변수에 Vercel 도메인 등록
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:*}